version: '2'

services:
  db:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    ports:
      - '${APP_DB_PORT}:5432'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_USERNAME=${USER}'

volumes:
  postgresql_data:
    driver: local
