[package]
name = "entities"
version = "0.1.0"
authors = ["resolritter <resolritter@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structout = "0.6"
surf = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
